import type { MundaneCategory, MundaneItem } from "./types";

/** PHB-style equipment from DungeonMasterTools items.html */
export const MUNDANE_ITEMS: MundaneItem[] = [
  { name: "Padded", costGp: 5, category: "armor", notes: "AC 11 + Dex mod; 8 lb." },
  { name: "Leather", costGp: 10, category: "armor", notes: "AC 11 + Dex mod; 10 lb." },
  { name: "Studded leather", costGp: 45, category: "armor", notes: "AC 12 + Dex mod; 13 lb." },
  { name: "Hide", costGp: 10, category: "armor", notes: "AC 12 + Dex mod (Max 2); 12 lb." },
  { name: "Chain shirt", costGp: 50, category: "armor", notes: "AC 13 + Dex mod (Max 2); 20 lb." },
  { name: "Scale mail", costGp: 50, category: "armor", notes: "AC 14 + Dex mod (Max 2); 45 lb." },
  { name: "Breastplate", costGp: 400, category: "armor", notes: "AC 14 + Dex mod (Max 2); 20 lb." },
  { name: "Half plate", costGp: 750, category: "armor", notes: "AC 15 + Dex mod (Max 2); 40 lb." },
  { name: "Ring mail", costGp: 30, category: "armor", notes: "AC 14; 40 lb." },
  { name: "Chain mail", costGp: 75, category: "armor", notes: "AC 16; 55 lb." },
  { name: "Splint", costGp: 200, category: "armor", notes: "AC 17; 60 lb." },
  { name: "Plate", costGp: 1500, category: "armor", notes: "AC 18; 65 lb." },
  { name: "Shield", costGp: 10, category: "shield", notes: "AC +2; 6 lb." },
  { name: "Club", costGp: 0.1, category: "weapon", notes: "1d4 B; 2 lb." },
  { name: "Dagger", costGp: 2, category: "weapon", notes: "1d4 P; 1 lb.; Finesse Weapon, Thrown Rg(20/60)" },
  { name: "Greatclub", costGp: 0.2, category: "weapon", notes: "1d8 B; 10 lb.; Two Handed" },
  { name: "Handaxe", costGp: 5, category: "weapon", notes: "1d6 S; 2 lb.; Thrown Rg(20/60)" },
  { name: "Javelin", costGp: 0.5, category: "weapon", notes: "1d6 P; 2 lb.; Thrown Rg(30/120)" },
  { name: "Light hammer", costGp: 2, category: "weapon", notes: "1d4 B; 2 lb.; Thrown Rg(20/60)" },
  { name: "Mace", costGp: 5, category: "weapon", notes: "1d6 B; 4 lb.; -" },
  { name: "Quarterstaff", costGp: 0.2, category: "weapon", notes: "1d6 B; 4 lb.; Versatile(1d8)" },
  { name: "Sickle", costGp: 1, category: "weapon", notes: "1d4 S; 2 lb." },
  { name: "Spear", costGp: 1, category: "weapon", notes: "1d6 P; 3 lb.; Thrown Rg(20/60), Versatile(1d8)" },
  { name: "Crossbow, light", costGp: 25, category: "weapon", notes: "1d8 P; 5 lb.; Ammunition, Rg(80/320), Two Handed" },
  { name: "Dart", costGp: 0.05, category: "weapon", notes: "1d4 P; 1/4 lb.; Finesse Weapon, Thrown Rg(20/60)" },
  { name: "Shortbow", costGp: 25, category: "weapon", notes: "1d6 P; 2 lb.; Ammunition, Rg(80/320), Two Handed" },
  { name: "Sling", costGp: 0.1, category: "weapon", notes: "1d4 B; —; Ammunition, Rg(320)" },
  { name: "Battleaxe", costGp: 10, category: "weapon", notes: "1d8 S; 4 lb.; Versatile(1d10)" },
  { name: "Flail", costGp: 10, category: "weapon", notes: "1d8 B; 2 lb.; -" },
  { name: "Glaive", costGp: 20, category: "weapon", notes: "1d10 S; 6 lb.; Reach, Two Handed" },
  { name: "Greataxe", costGp: 30, category: "weapon", notes: "1d12 S; 7 lb.; Two Handed" },
  { name: "Greatsword", costGp: 50, category: "weapon", notes: "2d6 S; 6 lb.; Two Handed" },
  { name: "Halberd", costGp: 20, category: "weapon", notes: "1d10 S; 6 lb.; Reach, Two Handed" },
  { name: "Lance", costGp: 10, category: "weapon", notes: "1d12 P; 6 lb.; Reach, Special" },
  { name: "Longsword", costGp: 15, category: "weapon", notes: "1d8 S; 3 lb.; Versatile(1d10)" },
  { name: "Maul", costGp: 10, category: "weapon", notes: "2d6 B; 10 lb.; Two Handed" },
  { name: "Morningstar", costGp: 15, category: "weapon", notes: "1d8 P; 4 lb.; -" },
  { name: "Pike", costGp: 5, category: "weapon", notes: "1d10 P; 18 lb.; Reach, Two Handed" },
  { name: "Rapier", costGp: 25, category: "weapon", notes: "1d8 P; 2 lb.; Finesse Weapon" },
  { name: "Scimitar", costGp: 25, category: "weapon", notes: "1d6 S; 3 lb.; Finesse Weapon" },
  { name: "Shortsword", costGp: 10, category: "weapon", notes: "1d6 P; 2 lb.; Finesse Weapon" },
  { name: "Trident", costGp: 5, category: "weapon", notes: "1d6 P; 4 lb.; Thrown Rg(20/60), Versatile(1d8)" },
  { name: "War pick", costGp: 5, category: "weapon", notes: "1d8 P; 2 lb.; -" },
  { name: "Warhammer", costGp: 15, category: "weapon", notes: "1d8 B; 2 lb.; Versatile(1d10)" },
  { name: "Whip", costGp: 2, category: "weapon", notes: "1d4 S; 3 lb.; Finesse Weapon, Reach" },
  { name: "Blowgun", costGp: 10, category: "weapon", notes: "1 P; 1 lb.; Ammunition, Rg(25/100)" },
  { name: "Crossbow, hand", costGp: 75, category: "weapon", notes: "1d6 P; 3 lb.; Ammunition, Rg(30/120)" },
  { name: "Crossbow, heavy", costGp: 50, category: "weapon", notes: "1d10 P; 18 lb.; Ammunition, Rg(100/400), Two Handed" },
  { name: "Longbow", costGp: 50, category: "weapon", notes: "1d8 P; 2 lb.; Ammunition, Rg(150,600), Two Handed" },
  { name: "Net", costGp: 1, category: "weapon", notes: "—; 3 lb.; Special, Thrown Rg(5/15)" },
  { name: "Alchemist's supplies", costGp: 50, category: "tool", notes: "8 lb." },
  { name: "Brewer's supplies", costGp: 20, category: "tool", notes: "9 lb." },
  { name: "Calligrapher's supplies", costGp: 10, category: "tool", notes: "5 lb." },
  { name: "Carpenter's tools", costGp: 8, category: "tool", notes: "6 lb." },
  { name: "Cartographer's tools", costGp: 15, category: "tool", notes: "6 lb." },
  { name: "Cobbler's tools", costGp: 5, category: "tool", notes: "5 lb." },
  { name: "Cook's utensils", costGp: 1, category: "tool", notes: "8 lb." },
  { name: "Glassblower's tools", costGp: 30, category: "tool", notes: "5 lb." },
  { name: "Jeweler's tools", costGp: 25, category: "tool", notes: "2 lb." },
  { name: "Leatherworker's tools", costGp: 5, category: "tool", notes: "5 lb." },
  { name: "Mason's tools", costGp: 10, category: "tool", notes: "8 lb." },
  { name: "Painter's supplies", costGp: 10, category: "tool", notes: "5 lb." },
  { name: "Potter's tools", costGp: 10, category: "tool", notes: "3 lb." },
  { name: "Smith's tools", costGp: 20, category: "tool", notes: "8 lb." },
  { name: "Tinker's tools", costGp: 50, category: "tool", notes: "10 lb." },
  { name: "Weaver's tools", costGp: 1, category: "tool", notes: "5 lb." },
  { name: "Woodcarver's tools", costGp: 1, category: "tool", notes: "5 lb." },
  { name: "Dice set", costGp: 0.1, category: "tool", notes: "—" },
  { name: "Dragonchess set", costGp: 1, category: "tool", notes: "1/2 lb." },
  { name: "Playing card set", costGp: 0.5, category: "tool", notes: "—" },
  { name: "Three-Dragon Ante set", costGp: 1, category: "tool", notes: "—" },
  { name: "Herbalism kit", costGp: 5, category: "tool", notes: "3 lb." },
  { name: "Bagpipes", costGp: 30, category: "tool", notes: "6 lb." },
  { name: "Drum", costGp: 6, category: "tool", notes: "3 lb." },
  { name: "Dulcimer", costGp: 25, category: "tool", notes: "10 lb." },
  { name: "Flute", costGp: 2, category: "tool", notes: "1 lb." },
  { name: "Lute", costGp: 35, category: "tool", notes: "2 lb." },
  { name: "Lyre", costGp: 30, category: "tool", notes: "2 lb." },
  { name: "Horn", costGp: 3, category: "tool", notes: "2 lb." },
  { name: "Pan flute", costGp: 12, category: "tool", notes: "2 lb." },
  { name: "Shawm", costGp: 2, category: "tool", notes: "1 lb." },
  { name: "Viol", costGp: 30, category: "tool", notes: "1 lb." },
  { name: "Navigator's tools", costGp: 25, category: "tool", notes: "2 lb." },
  { name: "Poisoner's kit", costGp: 50, category: "tool", notes: "2 lb." },
  { name: "Thieves' tools", costGp: 25, category: "tool", notes: "1 lb." },
  { name: "Disguise kit", costGp: 25, category: "tool", notes: "3 lb." },
  { name: "Forgery kit", costGp: 15, category: "tool", notes: "5 lb." },
  { name: "Abacus", costGp: 2, category: "gear", notes: "2 lb." },
  { name: "Acid (vial)", costGp: 25, category: "gear", notes: "1 lb." },
  { name: "Alchemist's fire (flask)", costGp: 50, category: "gear", notes: "1 lb." },
  { name: "Arrows (20)", costGp: 1, category: "gear", notes: "1 lb." },
  { name: "Blowgun needles (50)", costGp: 1, category: "gear", notes: "1 lb." },
  { name: "Crossbow bolts (20)", costGp: 1, category: "gear", notes: "1½ lb." },
  { name: "Sling bullets (20)", costGp: 0.04, category: "gear", notes: "1½ lb." },
  { name: "Antitoxin (vial)", costGp: 50, category: "gear", notes: "—" },
  { name: "Crystal", costGp: 10, category: "gear", notes: "1 lb." },
  { name: "Orb", costGp: 20, category: "gear", notes: "3 lb." },
  { name: "Rod", costGp: 10, category: "gear", notes: "2 lb." },
  { name: "Staff", costGp: 5, category: "gear", notes: "4 lb." },
  { name: "Wand", costGp: 10, category: "gear", notes: "1 lb." },
  { name: "Backpack", costGp: 2, category: "gear", notes: "5 lb." },
  { name: "Ball bearings (bag of 1,000)", costGp: 1, category: "gear", notes: "2 lb." },
  { name: "Barrel", costGp: 2, category: "gear", notes: "70 lb." },
  { name: "Basket", costGp: 0.4, category: "gear", notes: "2 lb." },
  { name: "Bedroll", costGp: 1, category: "gear", notes: "7 lb." },
  { name: "Bell", costGp: 1, category: "gear", notes: "—" },
  { name: "Blanket", costGp: 0.5, category: "gear", notes: "3 lb." },
  { name: "Block and tackle", costGp: 1, category: "gear", notes: "5 lb." },
  { name: "Book", costGp: 25, category: "gear", notes: "5 lb." },
  { name: "Bottle, glass", costGp: 2, category: "gear", notes: "2 lb." },
  { name: "Bucket", costGp: 0.05, category: "gear", notes: "2 lb." },
  { name: "Caltrops (bag of 20)", costGp: 1, category: "gear", notes: "2 lb." },
  { name: "Candle", costGp: 0.01, category: "gear", notes: "—" },
  { name: "Case, crossbow bolt", costGp: 1, category: "gear", notes: "1 lb." },
  { name: "Case, map or scroll", costGp: 1, category: "gear", notes: "1 lb." },
  { name: "Chain (10 feet)", costGp: 5, category: "gear", notes: "10 lb." },
  { name: "Chalk (1 piece)", costGp: 0.01, category: "gear", notes: "—" },
  { name: "Chest", costGp: 5, category: "gear", notes: "25 lb." },
  { name: "Climber's kit", costGp: 25, category: "gear", notes: "12 lb." },
  { name: "Clothes, common", costGp: 0.5, category: "gear", notes: "3 lb." },
  { name: "Clothes, costume", costGp: 5, category: "gear", notes: "4 lb." },
  { name: "Clothes, fine", costGp: 15, category: "gear", notes: "6 lb." },
  { name: "Clothes, traveler's", costGp: 2, category: "gear", notes: "4 lb." },
  { name: "Clothes, Cold Weather", costGp: 10, category: "gear", notes: "8 lb." },
  { name: "Component pouch", costGp: 25, category: "gear", notes: "2 lb." },
  { name: "Crowbar", costGp: 2, category: "gear", notes: "5 lb." },
  { name: "Sprig of mistletoe", costGp: 1, category: "gear", notes: "—" },
  { name: "Totem", costGp: 1, category: "gear", notes: "—" },
  { name: "Wooden staff", costGp: 5, category: "gear", notes: "4 lb." },
  { name: "Yew wand", costGp: 10, category: "gear", notes: "1 lb." },
  { name: "Fishing tackle", costGp: 1, category: "gear", notes: "4 lb." },
  { name: "Flask or tankard", costGp: 0.02, category: "gear", notes: "1 lb." },
  { name: "Grappling hook", costGp: 2, category: "gear", notes: "4 lb." },
  { name: "Hammer", costGp: 1, category: "gear", notes: "3 lb." },
  { name: "Hammer, sledge", costGp: 2, category: "gear", notes: "10 lb." },
  { name: "Healer's kit", costGp: 5, category: "gear", notes: "3 lb." },
  { name: "Amulet", costGp: 5, category: "gear", notes: "1 lb." },
  { name: "Emblem", costGp: 5, category: "gear", notes: "—" },
  { name: "Reliquary", costGp: 5, category: "gear", notes: "2 lb." },
  { name: "Holy water (flask)", costGp: 25, category: "gear", notes: "1 lb." },
  { name: "Hourglass", costGp: 25, category: "gear", notes: "1 lb." },
  { name: "Hunting trap", costGp: 5, category: "gear", notes: "25 lb." },
  { name: "Ink (1 ounce bottle)", costGp: 10, category: "gear", notes: "—" },
  { name: "Ink pen", costGp: 0.02, category: "gear", notes: "—" },
  { name: "Jug or pitcher", costGp: 0.02, category: "gear", notes: "4 lb." },
  { name: "Ladder (10-foot)", costGp: 0.1, category: "gear", notes: "25 lb." },
  { name: "Lamp", costGp: 0.5, category: "gear", notes: "1 lb." },
  { name: "Lantern, bullseye", costGp: 10, category: "gear", notes: "2 lb." },
  { name: "Lantern, hooded", costGp: 5, category: "gear", notes: "2 lb." },
  { name: "Lock", costGp: 10, category: "gear", notes: "1 lb." },
  { name: "Magnifying glass", costGp: 100, category: "gear", notes: "—" },
  { name: "Manacles", costGp: 2, category: "gear", notes: "6 lb." },
  { name: "Mess kit", costGp: 0.2, category: "gear", notes: "1 lb." },
  { name: "Mirror, steel", costGp: 5, category: "gear", notes: "1/2 lb." },
  { name: "Oil (flask)", costGp: 0.1, category: "gear", notes: "1 lb." },
  { name: "Paper (one sheet)", costGp: 0.2, category: "gear", notes: "—" },
  { name: "Parchment (one sheet)", costGp: 0.1, category: "gear", notes: "—" },
  { name: "Perfume (vial)", costGp: 5, category: "gear", notes: "—" },
  { name: "Pick, miner's", costGp: 2, category: "gear", notes: "10 lb." },
  { name: "Piton", costGp: 0.05, category: "gear", notes: "1/4 lb." },
  { name: "Poison, basic (vial)", costGp: 100, category: "gear", notes: "—" },
  { name: "Pole (10-foot)", costGp: 0.05, category: "gear", notes: "7 lb." },
  { name: "Pot, iron", costGp: 2, category: "gear", notes: "10 lb." },
  { name: "Potion of healing", costGp: 50, category: "gear", notes: "1/2 lb." },
  { name: "Pouch", costGp: 0.5, category: "gear", notes: "1 lb." },
  { name: "Quiver", costGp: 1, category: "gear", notes: "1 lb." },
  { name: "Ram, portable", costGp: 4, category: "gear", notes: "35 lb." },
  { name: "Rations (1 day)", costGp: 0.5, category: "gear", notes: "2 lb." },
  { name: "Robes", costGp: 1, category: "gear", notes: "4 lb." },
  { name: "Rope, hempen (50 feet)", costGp: 1, category: "gear", notes: "10 lb." },
  { name: "Rope, silk (50 feet)", costGp: 10, category: "gear", notes: "5 lb." },
  { name: "Sack", costGp: 0.01, category: "gear", notes: "1/2 lb." },
  { name: "Scale, merchant's", costGp: 5, category: "gear", notes: "3 lb." },
  { name: "Sealing wax", costGp: 0.5, category: "gear", notes: "—" },
  { name: "Shovel", costGp: 2, category: "gear", notes: "5 lb." },
  { name: "Signal whistle", costGp: 0.05, category: "gear", notes: "—" },
  { name: "Signet ring", costGp: 5, category: "gear", notes: "—" },
  { name: "Soap", costGp: 0.02, category: "gear", notes: "—" },
  { name: "Spellbook", costGp: 50, category: "gear", notes: "3 lb." },
  { name: "Spikes, iron (10)", costGp: 1, category: "gear", notes: "5 lb." },
  { name: "Spyglass", costGp: 1000, category: "gear", notes: "1 lb." },
  { name: "Tent, two-person", costGp: 2, category: "gear", notes: "20 lb." },
  { name: "Tinderbox", costGp: 0.5, category: "gear", notes: "1 lb." },
  { name: "Torch", costGp: 0.01, category: "gear", notes: "1 lb." },
  { name: "Vial", costGp: 1, category: "gear", notes: "—" },
  { name: "Waterskin", costGp: 0.2, category: "gear", notes: "5 lb. (full)" },
  { name: "Whetstone", costGp: 0.01, category: "gear", notes: "1 lb." },
  { name: "Camel", costGp: 50, category: "mount", notes: "50ft.; 480 lb" },
  { name: "Donkey or Mule", costGp: 8, category: "mount", notes: "40ft.; 420 lb" },
  { name: "Elephant", costGp: 200, category: "mount", notes: "40ft.; 1320 lb" },
  { name: "Horse, draft", costGp: 50, category: "mount", notes: "40ft.; 540 lb" },
  { name: "Horse, riding", costGp: 75, category: "mount", notes: "60ft.; 480 lb" },
  { name: "Mastiff", costGp: 25, category: "mount", notes: "40ft.; 195 lb" },
  { name: "Pony", costGp: 30, category: "mount", notes: "40ft.; 225 lb" },
  { name: "Warhorse", costGp: 400, category: "mount", notes: "60ft.; 540 lb" },
  { name: "Bit and bridle", costGp: 2, category: "vehicle", notes: "1 lb" },
  { name: "Carriage", costGp: 100, category: "vehicle", notes: "600 lb" },
  { name: "Cart", costGp: 15, category: "vehicle", notes: "200 lb" },
  { name: "Chariot", costGp: 250, category: "vehicle", notes: "100 lb" },
  { name: "Feed (per day)", costGp: 0.05, category: "vehicle", notes: "10 lb" },
  { name: "Exotic", costGp: 60, category: "vehicle", notes: "40 lb" },
  { name: "Military", costGp: 20, category: "vehicle", notes: "30 lb" },
  { name: "Pack", costGp: 5, category: "vehicle", notes: "15 lb" },
  { name: "Riding", costGp: 10, category: "vehicle", notes: "25 lb" },
  { name: "Saddlebags", costGp: 4, category: "vehicle", notes: "8 lb" },
  { name: "Sled", costGp: 20, category: "vehicle", notes: "300 lb" },
  { name: "Stabling (per day)", costGp: 0.5, category: "vehicle", notes: "-" },
  { name: "Wagon", costGp: 35, category: "vehicle", notes: "400 lb" },
  { name: "Galley", costGp: 30000, category: "vehicle", notes: "4 mph" },
  { name: "Keelboat", costGp: 3000, category: "vehicle", notes: "1 mph" },
  { name: "Longship", costGp: 10000, category: "vehicle", notes: "3 mph" },
  { name: "Rowboat", costGp: 50, category: "vehicle", notes: "1.5 mph" },
  { name: "Sailing Ship", costGp: 10000, category: "vehicle", notes: "2 mph" },
  { name: "Warship", costGp: 25000, category: "vehicle", notes: "2.5 mph" },
  { name: "Gallon", costGp: 0.2, category: "service" },
  { name: "Mug", costGp: 0.04, category: "service" },
  { name: "Banquet (per person)", costGp: 10, category: "service" },
  { name: "Bread, loaf", costGp: 0.02, category: "service" },
  { name: "Cheese, hunk", costGp: 0.1, category: "service" },
  { name: "Squalid", costGp: 0.07, category: "service" },
  { name: "Poor", costGp: 0.1, category: "service" },
  { name: "Modest", costGp: 0.5, category: "service" },
  { name: "Comfortable", costGp: 0.8, category: "service" },
  { name: "Wealthy", costGp: 2, category: "service" },
  { name: "Aristocratic", costGp: 4, category: "service" },
  { name: "Squalid", costGp: 0.03, category: "service" },
  { name: "Poor", costGp: 0.06, category: "service" },
  { name: "Modest", costGp: 0.3, category: "service" },
  { name: "Comfortable", costGp: 0.5, category: "service" },
  { name: "Wealthy", costGp: 0.8, category: "service" },
  { name: "Aristocratic", costGp: 2, category: "service" },
  { name: "Meat, chunk", costGp: 0.3, category: "service" },
  { name: "Common (pitcher)", costGp: 0.2, category: "service" },
  { name: "Fine (bottle)", costGp: 10, category: "service" },
  { name: "Between Towns", costGp: 0.03, category: "service" },
  { name: "Within a City", costGp: 0.01, category: "service" },
  { name: "Skilled", costGp: 2, category: "service" },
  { name: "Unskilled", costGp: 0.2, category: "service" },
  { name: "Messenger", costGp: 0.02, category: "service" },
  { name: "Road/Gate Toll", costGp: 0.01, category: "service" },
  { name: "Ship's Passage", costGp: 0.1, category: "service" },
  { name: "First Level Spell", costGp: 30, category: "service" },
  { name: "Second Level Spell", costGp: 50, category: "service" },
  { name: "Squalid", costGp: 0.1, category: "service" },
  { name: "Poor", costGp: 0.2, category: "service" },
  { name: "Modest", costGp: 1, category: "service" },
  { name: "Comfortable", costGp: 2, category: "service" },
  { name: "Wealthy", costGp: 4, category: "service" },
  { name: "Aristocratic", costGp: 10, category: "service" },
];

export function mundaneItemsByCategory(category: MundaneCategory): MundaneItem[] {
  return MUNDANE_ITEMS.filter((i) => i.category === category);
}

export function findMundaneItem(name: string): MundaneItem | undefined {
  const key = name.trim().toLowerCase();
  return MUNDANE_ITEMS.find((i) => i.name.toLowerCase() === key);
}
